# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('vehicle_reg_num', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon_pos', models.FloatField()),
                ('lat_pos', models.FloatField()),
                ('time_stamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transport.vehicle')),
            ],
        ),
    ]
