# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0002_vehicle_vehicle_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=200),
        ),
    ]
