# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0003_auto_20170209_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_live',
            name='time_stamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
