# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_date', models.DateTimeField(auto_now_add=True)),
                ('Booking_status', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_liscence', models.CharField(default=None, max_length=20)),
                ('Driver_longitude', models.FloatField(default=None)),
                ('Driver_latitude', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='My_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('My_user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1)),
                ('My_user_name', models.CharField(default=None, max_length=250)),
                ('My_user_phone', models.IntegerField(default=None)),
                ('My_user_addr', models.CharField(default=None, max_length=250)),
                ('My_user_email', models.CharField(default=None, max_length=250)),
                ('My_user_dateOfBirth', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Passenger_latitude', models.FloatField(default=None)),
                ('Passenger_longitude', models.FloatField(default=None)),
                ('Passenger_active', models.BooleanField(default=None)),
                ('Passenger_My_user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Transport.My_user')),
            ],
        ),
        migrations.CreateModel(
            name='Valid_stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valid_stop_name', models.CharField(default=None, max_length=50)),
                ('Valid_stop_latitude', models.FloatField(default=None)),
                ('Valid_stop_longitude', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_name', models.CharField(default=None, max_length=200)),
                ('Vehicle_latitude', models.FloatField(default=None)),
                ('Vehicle_longitude', models.FloatField(default=None)),
                ('Vehicle_rc', models.CharField(default=None, max_length=200)),
                ('Vehicle_active', models.BooleanField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='Driver_My_user',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='Transport.My_user'),
        ),
        migrations.AddField(
            model_name='driver',
            name='Driver_currentVehicle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Transport.Vehicle'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Booking_destination',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='booking_destination_point', to='Transport.Valid_stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Booking_passanger',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Transport.My_user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Booking_startpoint',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='booking_starting_point', to='Transport.Valid_stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Booking_vehicle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Transport.Vehicle'),
        ),
    ]
