# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Booking_passanger',
        ),
        migrations.AddField(
            model_name='booking',
            name='Booking_passenger',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Transport.Passenger'),
        ),
        migrations.AlterField(
            model_name='my_user',
            name='My_user_dateOfBirth',
            field=models.DateField(default=None, null=True),
        ),
    ]
