# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0003_auto_20170310_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_destination',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_startpoint',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
